# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI with Gradle

# events
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

# groups a set of actions that can be executed
# the name is arbitrary
jobs:
  build:
    
    # in order to test on all 3 different os
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubunto-latest, windows-latest, macOS-latest]

    steps:
    # a predefined action
    # use is selected for actions
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
      with:
        arguments: build
    
  publish:
    # this is useful for ordeing the jobs
    # here we say don't run them in parallel
    needs: build
  
